version: '3.5'

services:
  ### XDeen's Workspace ################################################
  xdeen:
    image: sheriflight/xdeen:latest
    depends_on:
      - postgres
      - redis
    tty: true
    env_file:
      - ../.env
    ports:
      - "9000:9000"
      # Jupyter Port
      - "8888:8888"
    volumes:
      - ../:/home
    container_name: xdeen
    command: bash -c "xdeen install-live --no-strict && xdeen run"

  ### PostgreSQL ################################################
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=xdeen_user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=xdeen_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    container_name: postgres

  ### Redis ################################################
  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    container_name: redis
    
volumes:
  postgres-data:
